version: "3"
services:
  blogx:
    image: mwbowo/blogx:1.0
    container_name: web-blogx
    restart: always
    volumes:
      - ./.env.example:/blogx/.env
    ports:
      - 8000:8000
    command: 'php artisan serve --host=0.0.0.0'
